<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader');
$pontuacao= Data::get('pontos')
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

 <p></p>
 <br>
 <br>
 <br>
 <br>
 
 <div align="center">
 <h1> Highscores </h1>
     <table width="25%">
        <tr>
         <th>Username</th>
         <th>Pontos</th>
        </tr>
     </table>
     <?php
     $i=10;

     foreach ($pontuacao as $p) {

         ?>
         <table width="23%">

             <tr>
                 <td><?=$p->users->username?> </td>
                 <td><?=$p->pontos?></td>
                 <hr style="width:25%;">
             </tr>
         </table>
    <!-- <table>
         <tr>
             <th> <span style="margin-left"></span><b>Username</b></span></th>
         </tr>
         <td><//?=$p->users->username?></td> -
         <th> <span style="margin-right"><b>Pontos</b></span></th>
         <td><//?=$p->pontos?></td>
            <br>
     </table>-->

           <?php } ?>
     <?php
      {
         ?>


         <br>

     <?php } ?>
 </div>
 <?php Layout::includeLayout('footer')?>
</body>
</html>