<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); 
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

 <p></p>
 <br>
 <br>
 <br>
 <br>
 
 <div align="center">
 <h1> Highscores </h1>


     <span style="margin-left"></span><b>Username</b></span>

     <span style="margin-right"><b>Pontos</b></span>

 </div>
 <?php Layout::includeLayout('footer')?>
</body>
</html>
