<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader');
$pontuacao= Data::get('pontos')
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    

 <p></p>
 <br>
 <br>
 <br>
 <br>
 
 <div align="center">
 <h1> Highscores </h1>

     <?php
     $i=10;

     foreach ($pontuacao as $p) {

         ?>

     <span style="margin-left"></span><b>Username</b></span>
     <?=$p->users->username?> -
             <span style="margin-right"><b>Pontos</b></span>
             <?=$p->pontos?>
            <br>


           <?php } ?>
     <?php
      {
         ?>


         <br>

     <?php } ?>
 </div>
 <?php Layout::includeLayout('footer')?>
</body>
</html>