<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('header');
$registo = Data::get('informacao') ?>
<?php ErrMgr::attach($registo)?>

<?php  Tracy\Debugger::barDump($registo);
?>

<div align="center">
    <h1 class="page-title"><b>Perfil</b></h1>
<div name="Perfilcentro">


                            <form method="Post" action="<?= URL::toRoute('home/perfil')?>">
                                Nome Completo
                                <input type="text" value="<?=$registo->nomecompleto?>" name="nomecompleto" placeholder="John Smith" required/>
                                <?= ErrMgr::bind('nomecompleto') ?>
                                <br><br>
                                Email
                                <input type="email" value="<?=$registo->email?>" name="email" placeholder ="John@hotmail.com" required/>
                                <?= ErrMgr::bind('email') ?>
                                <br><br>

                                Data Nascimento
                                <input type="date" value="<?=$registo->datanascimento?>" name="data" required/>
                                <?= ErrMgr::bind('datanascimento') ?>
                                <br><br>

                                Password
                                <input type="password" value="<?=$registo->password?>" name="password" required/>
                                <?= ErrMgr::bind('password') ?>
                                <br><br>



                                <input type="submit" value="Atualizar">
</div>
                            </form>
</div>



<?php Layout::includeLayout('footer') ?>