<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Data;
Layout::includeLayout('indexheader'); 
?>

    

 <p></p>
 <br>
 <br>
 <br>
 <br>
 
 <div align="center">
 <h1> Register </h1>
</div>
<p>

    <?php $registo = Data::get('informacao')?>
    <?php ErrMgr::attach($registo) ?>

<br><br><br><br><br>
<form method="Post" action="<?= URL::toRoute('home/registar') ?>">
<div align="center">
Username
<input type="text" value="<?=$registo->username?>" name="username" placeholder="John" required/>
    <?= ErrMgr::bind('username') ?>
<br><br>

Nome Completo
<input type="text" value="<?=$registo->nomecompleto?>" name="nomecompleto" placeholder="John Smith" required/>
    <?= ErrMgr::bind('nomecompleto') ?>
<br><br>
Email
<input type="email" value="<?=$registo->email?>" name="email" placeholder ="John@hotmail.com" required/>
    <?= ErrMgr::bind('email') ?>
<br><br>

Data Nascimento
<input type="date" value="<?=$registo->datanascimento?>" name="data" required/>
    <?= ErrMgr::bind('datanascimento') ?>
<br><br>

Password
<input type="password" name="password" placeholder ="password" required/>
<br><br>

<input type="submit" value="Registar">
</form>
</div>
     <?php Layout::includeLayout('footer') ?>
