<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


<p></p>
<br>
<br>
<br>
<br>

<div align="center">;
    <h1> Backoffice </h1>;
</div>
<p>
    <br><br><br><br><br>
<form>
    <div align="center">
        Username
        <input type="text" name="Username" placeholder="John"/>
        <br><br>

        Password
        <input type="password"name="Password" placeholder ="password"/>
        <br><br>
        <input type="submit">
    </div>

</body>
</html>