<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $registo = Data::get('informacao')?>
<?php ErrMgr::attach($registo) ?>


	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">New User</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<hr>
							<form method="post" action="<?=Url::toRoute('backoffice/create')?>">
								<div class="top-margin">
									<label>Username <span class="text-danger">*</span></label>
									<input type="text" value="<?=$registo->username?>" name="username" class="form-control" placeholder="Enter Username">
                                    <?= ErrMgr::bind('username') ?>

								</div>
                                <div class="top-margin">
                                    <label>Nome Completo <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$registo->nomecompleto?>" name="nomecompleto" class="form-control" placeholder="Enter Nome Completo">
                                    <?= ErrMgr::bind('nomecompleto') ?>

                                </div>

                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input type="email" value="<?=$registo->email?>" name="email" class="form-control" placeholder="Enter Email">
                                    <?= ErrMgr::bind('email') ?>

                                </div>

                                <div class="top-margin">
                                    <label>Data Nascimento <span class="text-danger">*</span></label>
                                    <input type="date" value="<?=$registo->datanascimento?>" name="datanascimento" class="form-control"
                                    <?= ErrMgr::bind('datanascimento') ?>

                                </div>

                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input type="password" value="<?=$registo->password?>" name="password" class="form-control" placeholder="Enter Password">
                                    <?= ErrMgr::bind('password') ?>
                                </div>

								<div class="top-margin">
									<label>Ativacao <span class="text-danger">*</span></label>
									<input type="text" value="<?=$registo->ativacao?>" name="ativacao" class="form-control" placeholder="Enter Ativacao">
                                    <?= ErrMgr::bind('ativacao') ?>
                                </div>

                                <div class="top-margin">
                                    <label>Admin <span class="text-danger">*</span></label>
                                    <input type="text" value="<?=$registo->admin?>" name="admin" class="form-control" placeholder="Enter Admin">
                                    <?= ErrMgr::bind('admin') ?>
                                </div>

								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">New</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>