<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $registo = Data::get('informacao')?>
<?php ErrMgr::attach($registo) ?>

    <!-- container -->
    <div class="container">

        <div class="row">

            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <header class="page-header">
                    <h1 class="page-title">Edit Book</h1>
                </header>


                <div class="panel panel-default">
                    <div class="panel-body">

                        <hr>


                        <form class="form-horizontal" method="post" action="<?=Url::toRoute('backoffice/editar', $registo->id)?>">

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Name:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" value="<?=$registo->username?>" class="form-control" required name="username" placeholder="Enter username">
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-sm-2" for="name">Ativacao:<span class="text-danger">*</span></label>
                                <div class="col-sm-6">
                                    <input type="text" required value="<?=$registo->ativacao?>" class="form-control" name="ativacao" placeholder="Enter Ativacao">
                                </div>
                            </div>


                            <hr>

                            <div class="col-lg-4 text-right">
                                <button class="btn btn-default" type="submit">Save</button>
                            </div>
                    </div>
                    </form>
                </div>
        </div>



        </article>
        <!-- /Article -->

    </div>
    </div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>