<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $registos = Data::get('informacao')?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">User Index</li>
        </ol>

        <h2 class="text-left top-space">User Index</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Id</h3></th><th><h3>Name</h3></th><th><h3>Ativacao</h3></th><th><h3>User Actions</h3></th></thead>
                    <tbody>
                    <?php foreach ($registos as $registo) { ?>

                        <tr>
                            <?php\Tracy\Debugger::barDump($registo)?>
                            <td><?=$registo->id?></td>

                            <td><?=$registo->username?></td>
                            <td><?=$registo->ativacao?></td>
                            <td>
                                <a href="<?=Url::toRoute('backoffice/show', $registo->id)?>" class="btn btn-info" role="button">Show</a>
                                <a href="<?=Url::toRoute('backoffice/editar', $registo->id)?>" class="btn btn-info" role="button">Edit</a>
                                <a href="<?=Url::toRoute('backoffice/destroy', $registo->id)?>" class="btn btn-warning" role="button">Delete</a>
                            </td>
                        </tr>
                    <?php } ?>

                    </tbody>

                </table>

            </div>
            <div class="col-sm-6">

            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>