<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('header') ?>
<?php $registo = Data::get('informacao')?>
<?php ErrMgr::attach($registo) ?>

	<!-- container -->
	<div class="container">

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Ver utilizador</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<hr>
							
							<form method="post" action="<?=Url::toRoute('backoffice/index2')?>">
								<div class="top-margin">
									<label>Username <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$registo->username?>" name="name" class="form-control">
								</div>

                                <div class="top-margin">
                                    <label>Nome Completo <span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$registo->nomecompleto?>" name="nomecompleto" class="form-control">
                                </div>

                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input readonly="true" type="email" value="<?=$registo->email?>" name="email" class="form-control">
                                </div>

                                <div class="top-margin">
                                    <label>Data nascimento <span class="text-danger">*</span></label>
                                    <input readonly="true" type="date" value="<?=$registo->datanascimento?>" name="datanascimento" class="form-control">
                                </div>

								<div class="top-margin">
									<label>Ativacao <span class="text-danger">*</span></label>
									<input readonly="true" type="text" value="<?=$registo->ativacao?>" name="ativacao" class="form-control">
                                </div>

                                <div class="top-margin">
                                    <label>Admin<span class="text-danger">*</span></label>
                                    <input readonly="true" type="text" value="<?=$registo->admin?>" name="admin" class="form-control">
                                </div>

								<hr>

									<div class="col-lg-4 text-right">
										<button class="btn btn-action" type="submit">Return</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>